name: CI

on:
  push:
    branches:
      - main

jobs:
  lint-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python -m pip install pip-tools

    - name: Install pip-tools
      run: python -m pip install pip-tools

    - name: Generate requirements.txt
      run: pip-compile requirements.in

    - name: Run linter and static analysis
      run: |
        pylint mainTool.py
        pylint search_repository.py
        pylint rate_limit.py
        pylint rate_limit_handler.py
        pylint function_filter.py
        pylint pull_req_with_parameters.py
        pylint issue_handler.py
        pylint issues_with_parameters.py
        pylint import_and_save_workflow_logs.py
        pylint import_issue_without_comments.py
        pylint import_pull_request_without_comments.py
        pylint import_pull_requests.py
        pylint request_error_handler.py
        
    

  
